### ISSUE TITLE
Dúvida: Como atualizar as modificações?

### ISSUE THREAD

**Issue by oliiveiraaa** [Next-Panel/Jexactyl-BR#214]
Realizei a modificação de um texto no painel, porém tentei os comando de php artisan view:clear, etc, e não atualizou. Tentei utilizar o yarn e também não deu muito certo, poderia me ajudar?

**Comment by drysius** [comment]
@oliiveiraaa, o painel é dividido em três partes, uma é a views que é a parte mais "administrativa", a "scripts" que é a parte onde o client vê, e a "app" que é onde respostas de api e coisas do tipo, se você tiver mexido na "app" ou na "views" um php:clear deveria resolver, caso tu mexa na scripts , se tem que recompilar o react, usando

```bash
cd /var/www/jexactyl
yarn install
yarn run build:production
```

Espero que isso ajude, caso o texto que você modificou seja alguma tradução em causa, nós avise, assim poderemos colocar no painel principal para outras pessoas usarem também :3

**Comment by oliiveiraaa** [comment]
> @oliiveiraaa, o painel é dividido em três partes, uma é a views que é a parte mais "administrativa", a "scripts" que é a parte onde o client vê, e a "app" que é onde respostas de api e coisas do tipo, se você tiver mexido na "app" ou na "views" um php:clear deveria resolver, caso tu mexa na scripts , se tem que recompilar o react, usando
> 
> ```shell
> cd /var/www/jexactyl
> yarn install
> yarn run build:production
> ```
> 
> Espero que isso ajude, caso o texto que você modificou seja alguma tradução em causa, nós avise, assim poderemos colocar no painel principal para outras pessoas usarem também :3

root@localhost:/var/www/jexactyl# cd /var/www/jexactyl
yarn install
yarn run build:production
yarn install v1.22.21
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.67s.
yarn run v1.22.21
$ yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production
$ cd public/assets && find . \( -name "*.js" -o -name "*.map" \) -type f -delete
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/var/www/jexactyl/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/jexactyl/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/jexactyl/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/jexactyl/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/jexactyl/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/var/www/jexactyl/node_modules/source-map-loader/dist/index.js:37:5)
    at LOADER_EXECUTION (/var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/var/www/jexactyl/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/var/www/jexactyl/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /var/www/jexactyl/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /var/www/jexactyl/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

@drylian Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


Esperando sua resposta. Obrigado!

**Comment by oliiveiraaa** [comment]
Problema resolvido, obrigado pela atenção!
